public class EZQAdditionalInfoWrapper {
    public string lawyer_join_past_12m_cbx{get;set;}
    public string pl_claim_12m_not_reported_cbx{get;set;}
    public Double pl_claim_12m_not_reported_num{get;set;}
    public string aware_of_claim_cbx{get;set;}
    public Double aware_of_claim_num{get;set;}
    public string disciplinary_investegation_cbx{get;set;}
    public string disciplinary_bar_denied_cbx{get;set;}
    public string  disciplinary_sanctioned_cbx{get;set;}
    public string disciplinary_reprimanded_cbx{get;set;}
    public string disciplinary_censured_cbx{get;set;}
    public string disciplinary_suspended_cbx{get;set;}
    public string disciplinary_disbarred_cbx{get;set;}
    public string disciplinary_other_cbx{get;set;}
    public string disciplinary_open_num{get;set;}
    public string disciplinary_closed_num{get;set;}
    
}